const translations = {

  /* ══════════════════════════════════════════════════════════
     ENGLISH
  ══════════════════════════════════════════════════════════ */
  en: {
    // Nav / Footer
    footerPrivacy: "Privacy Policy", footerTerms: "Terms & Conditions",
    footerSupport: "Support & FAQ", footerRights: "© 2026 TapSOS. All rights reserved.",

    // Index
    heroTitle: "Emergency Help, One Tap Away",
    heroDesc: "TapSOS is the simplest, most accessible emergency app designed for everyone — especially seniors. Trigger a loud siren, call emergency services, and share your GPS location via WhatsApp instantly.",
    btnApple: "App Store", btnGoogle: "Google Play",
    feat1Title: "Instant SOS Alarm", feat1Desc: "One tap activates a powerful siren at full volume.",
    feat2Title: "Emergency Call", feat2Desc: "Calls your pre-configured emergency number directly.",
    feat3Title: "WhatsApp Location", feat3Desc: "Sends your real-time GPS coordinates to up to 5 contacts.",
    feat4Title: "Shake to Activate", feat4Desc: "Shake your phone to trigger the alarm hands-free.",
    feat5Title: "Home Screen Widget", feat5Desc: "Place SOS buttons on your home screen for instant access.",
    feat6Title: "10 Alarm Sounds", feat6Desc: "Choose from 10 different siren sounds.",

    // Privacy
    privTitle: "Privacy Policy",
    privEffective: "Effective Date: June 1, 2026",
    priv1Title: "1. Introduction",
    priv1Body: "Welcome to TapSOS. We respect your privacy and are committed to protecting it. TapSOS is built on a privacy-by-design philosophy: we do not collect, store, or transmit your personal data to our servers. All critical functions are performed locally on your device.",
    priv2Title: "2. Data We Do NOT Collect",
    priv2Body: "We do not require account registration, email, or any personal identification. We have no servers or databases storing your data.",
    priv3Title: "3. Device Features Used Locally",
    priv3Body: "TapSOS requests access to certain device features that never leave your device unless you trigger them:",
    priv3Li1: "Location (GPS): Used only to generate a Google Maps link sent via WhatsApp when you press the SOS button. Not tracked in the background.",
    priv3Li2: "Phone / Dialer: Used solely to dial the emergency number you configure.",
    priv3Li3: "Contacts: Used only within the app to let you select WhatsApp emergency contacts from your address book.",
    priv3Li4: "Motion Sensors: Used locally to detect phone shaking (shake-to-activate feature). Never transmitted.",
    priv4Title: "4. Advertising (Google AdMob)",
    priv4Body: "To keep TapSOS free, we use Google AdMob. AdMob may collect advertising identifiers and usage data to serve ads. You will be shown a consent dialog on first launch. You can update your preferences anytime via Settings › Ad Privacy Settings.",
    priv4Link: "Learn more about how Google uses data.",
    priv5Title: "5. Data Security",
    priv5Body: "Because we store nothing remotely, there is no server-side breach risk. Your configurations (emergency number, contacts, preferences) are stored securely in your device's local storage.",
    priv6Title: "6. Changes to This Policy",
    priv6Body: "We may update this Privacy Policy periodically. Changes will be reflected by updating the Effective Date above.",
    priv7Title: "7. Contact",
    priv7Body: "Questions? Contact us at:",

    // Terms
    termsTitle: "Terms & Conditions",
    termsEffective: "Effective Date: June 1, 2026",
    terms1Title: "1. Acceptance",
    terms1Body: "By downloading or using TapSOS, you agree to these Terms. If you do not agree, please uninstall the app.",
    terms2Title: "2. Description of Service",
    terms2Body: "TapSOS is a utility app that helps users in emergencies by triggering a siren, dialing a phone number, and sharing GPS location via WhatsApp.",
    terms2Disclaimer: "IMPORTANT DISCLAIMER: TapSOS is a supplementary emergency tool. It is NOT a replacement for official emergency services (112, 911, 999, etc.). We cannot guarantee the app will function in all situations (no battery, no signal, hardware failure). Always contact official emergency services first.",
    terms3Title: "3. User Responsibilities",
    terms3Li1: "Configuration: It is your responsibility to enter correct emergency numbers and contacts in Settings.",
    terms3Li2: "Permissions: Denying required permissions may prevent life-saving features from working.",
    terms3Li3: "Device: App functionality depends on device hardware, battery, and network availability.",
    terms3Li4: "Phone Format: WhatsApp contacts must include their international country code (e.g. +34 for Spain, +1 for USA).",
    terms4Title: "4. Limitation of Liability",
    terms4Body: "To the maximum extent permitted by law, the creators of TapSOS shall not be liable for any damages arising from the use or inability to use the app, including personal injury or loss of life resulting from reliance on the app during an emergency.",
    terms5Title: "5. Third-Party Services",
    terms5Li1: "WhatsApp (Meta): Sending location messages via WhatsApp is subject to WhatsApp's own Terms of Service.",
    terms5Li2: "Google AdMob: Advertisements are governed by Google's advertising policies.",
    terms6Title: "6. Intellectual Property",
    terms6Body: "All intellectual property in TapSOS — design, code, graphics — is owned by its developers. You may not copy, reverse-engineer, or redistribute the app without permission.",
    terms7Title: "7. Changes to Terms",
    terms7Body: "We may modify these Terms at any time. Continued use of the app constitutes acceptance of updated terms.",
    terms8Title: "8. Contact",
    terms8Body: "Questions? Reach us at:",

    // Support
    supportTitle: "Support & FAQ",
    supportDesc: "Need help? Find answers below or send us a message.",
    supportBtn: "Send Email",

    // FAQ
    faqTitle: "Frequently Asked Questions",
    faq1q: "Does TapSOS need an internet connection?",
    faq1a: "Only for sending the WhatsApp location message. The SOS siren, vibration, and emergency phone call work completely offline.",
    faq2q: "Is my personal data stored on a server?",
    faq2a: "No. TapSOS stores everything locally on your device. We have no servers holding your data. Your emergency number, contacts, and preferences never leave your phone.",
    faq3q: "How do I set up emergency contacts for WhatsApp?",
    faq3a: "Go to Settings › WhatsApp Contacts › Add from contacts. Select a person from your address book. Important: the number must include the international country code (e.g. +34 610 848 487 for Spain). You can add up to 5 contacts.",
    faq4q: "The WhatsApp button is not working. What should I do?",
    faq4a: "Check the following: 1) WhatsApp is installed on your phone. 2) You have added at least one WhatsApp contact in Settings. 3) Location (GPS) is enabled in your phone settings. 4) The contact's phone number includes the country code (e.g. +34, +1, +44).",
    faq5q: "How do I change the alarm sound?",
    faq5a: "Go to Settings › Alarm Sound. You will see sounds 1 through 10. Tap the play button (▶) next to any sound to preview it. Tap the number to select it, then press Save.",
    faq6q: "How does 'Shake to Activate' work?",
    faq6a: "When enabled, shaking your phone quickly 2–3 times triggers the SOS alarm automatically — useful when your hands are occupied or you cannot look at the screen. You can turn this feature on or off in Settings.",
    faq7q: "The app says 'Location Permission Denied'. How do I fix it?",
    faq7a: "Go to your phone's Settings › Apps › TapSOS › Permissions › Location › Select 'Allow only while using the app'. Then return to TapSOS and try again. If GPS is turned off, enable it from your phone's quick settings panel.",
    faq8q: "How do I set the emergency call number?",
    faq8a: "Go to Settings › Emergency Number and enter the number for your country (e.g. 112 in Europe, 911 in USA/Mexico, 999 in UK, 000 in Australia). The app tries to detect your country automatically, but you can always change it manually.",
    faq9q: "How do I add the TapSOS widget to my home screen?",
    faq9a: "On Android: long-press an empty area of your home screen › Widgets › TapSOS. Place the widget. It shows SOS, Call, and WhatsApp buttons directly on your home screen. On iOS: this requires the Widget Extension set up in Xcode (in progress).",
    faq10q: "Is TapSOS free? Are there subscriptions?",
    faq10a: "TapSOS is completely free to download and use. It is supported by unobtrusive banner advertisements (Google AdMob). There are no subscriptions, no in-app purchases, and no hidden costs.",
  },

  /* ══════════════════════════════════════════════════════════
     ESPAÑOL
  ══════════════════════════════════════════════════════════ */
  es: {
    footerPrivacy: "Política de Privacidad", footerTerms: "Términos y Condiciones",
    footerSupport: "Soporte y FAQ", footerRights: "© 2026 TapSOS. Todos los derechos reservados.",

    heroTitle: "Ayuda de Emergencia a un Toque",
    heroDesc: "TapSOS es la app de emergencias más accesible, diseñada para todos — especialmente mayores. Activa una sirena, llama a emergencias y comparte tu ubicación GPS por WhatsApp al instante.",
    btnApple: "App Store", btnGoogle: "Google Play",
    feat1Title: "Alarma SOS Instantánea", feat1Desc: "Un toque activa una potente sirena a volumen máximo.",
    feat2Title: "Llamada de Emergencia", feat2Desc: "Llama directamente a tu número de emergencia configurado.",
    feat3Title: "Ubicación por WhatsApp", feat3Desc: "Envía tus coordenadas GPS en tiempo real a hasta 5 contactos.",
    feat4Title: "Agitar para Activar", feat4Desc: "Agita el teléfono para activar la alarma sin tocar la pantalla.",
    feat5Title: "Widget en Escritorio", feat5Desc: "Pon los botones SOS en tu pantalla de inicio para acceso inmediato.",
    feat6Title: "10 Sonidos de Alarma", feat6Desc: "Elige entre 10 sirenas diferentes.",

    privTitle: "Política de Privacidad",
    privEffective: "Fecha de entrada en vigor: 1 de junio de 2026",
    priv1Title: "1. Introducción",
    priv1Body: "Bienvenido a TapSOS. Respetamos tu privacidad y nos comprometemos a protegerla. TapSOS está construido bajo la filosofía de privacidad por diseño: no recopilamos, almacenamos ni transmitimos tus datos personales a nuestros servidores. Todas las funciones críticas se ejecutan localmente en tu dispositivo.",
    priv2Title: "2. Datos que NO Recopilamos",
    priv2Body: "No requerimos registro de cuenta, correo electrónico ni ningún dato de identificación personal. No tenemos servidores ni bases de datos que almacenen tus datos.",
    priv3Title: "3. Funciones del Dispositivo Usadas Localmente",
    priv3Body: "TapSOS solicita acceso a ciertas funciones del dispositivo que nunca abandonan tu teléfono a menos que tú las actives:",
    priv3Li1: "Ubicación (GPS): Solo para generar un enlace de Google Maps enviado por WhatsApp al pulsar el botón SOS. No se rastrea en segundo plano.",
    priv3Li2: "Teléfono / Marcador: Solo para marcar el número de emergencia que configures.",
    priv3Li3: "Contactos: Solo dentro de la app para seleccionar contactos de emergencia de WhatsApp desde tu agenda.",
    priv3Li4: "Sensores de movimiento: Para detectar el agitado del teléfono (función agitar para activar). Nunca se transmite.",
    priv4Title: "4. Publicidad (Google AdMob)",
    priv4Body: "Para mantener TapSOS gratuito, usamos Google AdMob. AdMob puede recopilar identificadores publicitarios y datos de uso. Al primer inicio se mostrará un diálogo de consentimiento. Puedes actualizar tus preferencias en Ajustes › Opciones de Privacidad (Anuncios).",
    priv4Link: "Más información sobre cómo Google usa los datos.",
    priv5Title: "5. Seguridad de Datos",
    priv5Body: "Al no almacenar nada de forma remota, no hay riesgo de filtraciones en nuestros servidores. Tu configuración (número de emergencia, contactos, preferencias) se guarda de forma segura en el almacenamiento local de tu dispositivo.",
    priv6Title: "6. Cambios en Esta Política",
    priv6Body: "Podemos actualizar esta Política de Privacidad periódicamente. Los cambios se reflejarán actualizando la Fecha de entrada en vigor.",
    priv7Title: "7. Contacto",
    priv7Body: "¿Preguntas? Escríbenos a:",

    termsTitle: "Términos y Condiciones",
    termsEffective: "Fecha de entrada en vigor: 1 de junio de 2026",
    terms1Title: "1. Aceptación",
    terms1Body: "Al descargar o usar TapSOS, aceptas estos Términos. Si no estás de acuerdo, desinstala la app.",
    terms2Title: "2. Descripción del Servicio",
    terms2Body: "TapSOS es una app de utilidades que ayuda en emergencias activando una sirena, marcando un número de teléfono y compartiendo la ubicación GPS por WhatsApp.",
    terms2Disclaimer: "AVISO IMPORTANTE: TapSOS es una herramienta de emergencia complementaria. NO es un sustituto de los servicios de emergencia oficiales (112, 911, etc.). No podemos garantizar su funcionamiento en todas las situaciones (batería agotada, sin señal, fallo de hardware). Contacta siempre con los servicios de emergencia oficiales.",
    terms3Title: "3. Responsabilidades del Usuario",
    terms3Li1: "Configuración: Es tu responsabilidad introducir números de emergencia y contactos correctos en Ajustes.",
    terms3Li2: "Permisos: Denegar permisos puede impedir que funcionen las funciones de seguridad.",
    terms3Li3: "Dispositivo: La funcionalidad depende del hardware, batería y conectividad del dispositivo.",
    terms3Li4: "Formato de teléfono: Los contactos de WhatsApp deben incluir el prefijo internacional (ej. +34 para España).",
    terms4Title: "4. Limitación de Responsabilidad",
    terms4Body: "En la máxima medida permitida por la ley, los creadores de TapSOS no serán responsables de ningún daño derivado del uso o imposibilidad de uso de la app, incluyendo lesiones personales o pérdida de vida por confiar en la app durante una emergencia.",
    terms5Title: "5. Servicios de Terceros",
    terms5Li1: "WhatsApp (Meta): El envío de mensajes de ubicación está sujeto a los propios Términos de Servicio de WhatsApp.",
    terms5Li2: "Google AdMob: La publicidad se rige por las políticas de publicidad de Google.",
    terms6Title: "6. Propiedad Intelectual",
    terms6Body: "Toda la propiedad intelectual de TapSOS — diseño, código, gráficos — pertenece a sus desarrolladores. No puedes copiar, descompilar ni redistribuir la app sin permiso.",
    terms7Title: "7. Cambios en los Términos",
    terms7Body: "Podemos modificar estos Términos en cualquier momento. El uso continuado de la app implica la aceptación de los términos actualizados.",
    terms8Title: "8. Contacto",
    terms8Body: "¿Preguntas? Contáctanos en:",

    supportTitle: "Soporte y FAQ",
    supportDesc: "¿Necesitas ayuda? Encuentra respuestas a continuación o escríbenos.",
    supportBtn: "Enviar Email",

    faqTitle: "Preguntas Frecuentes",
    faq1q: "¿TapSOS necesita conexión a internet?",
    faq1a: "Solo para enviar el mensaje de ubicación por WhatsApp. La sirena SOS, la vibración y la llamada de emergencia funcionan completamente sin internet.",
    faq2q: "¿Mis datos personales se guardan en algún servidor?",
    faq2a: "No. TapSOS guarda todo localmente en tu dispositivo. No tenemos servidores con tus datos. Tu número de emergencia, contactos y preferencias no salen de tu teléfono.",
    faq3q: "¿Cómo configuro los contactos de emergencia para WhatsApp?",
    faq3a: "Ve a Ajustes › Contacto de WhatsApp › Añadir desde la agenda. Selecciona una persona. Importante: el número debe incluir el prefijo internacional (ej. +34 610 848 487 para España). Puedes añadir hasta 5 contactos.",
    faq4q: "El botón de WhatsApp no funciona. ¿Qué hago?",
    faq4a: "Comprueba: 1) Que WhatsApp esté instalado. 2) Que hayas añadido al menos un contacto en Ajustes. 3) Que el GPS/Ubicación esté activado en tu teléfono. 4) Que el número del contacto incluya el prefijo (+34, +1, +44, etc.).",
    faq5q: "¿Cómo cambio el sonido de alarma?",
    faq5a: "Ve a Ajustes › Sonido de alarma. Verás los sonidos del 1 al 10. Pulsa el botón de reproducción (▶) junto a cualquier sonido para escucharlo antes de elegir. Pulsa el número para seleccionarlo y luego guarda.",
    faq6q: "¿Cómo funciona 'Agitar para activar'?",
    faq6a: "Cuando está activada, agitar el teléfono rápidamente 2-3 veces activa la alarma SOS automáticamente — útil cuando tienes las manos ocupadas o no puedes mirar la pantalla. Puedes activar o desactivar esta función en Ajustes.",
    faq7q: "La app dice 'Permiso de ubicación denegado'. ¿Cómo lo soluciono?",
    faq7a: "Ve a los Ajustes de tu teléfono › Aplicaciones › TapSOS › Permisos › Ubicación › Selecciona 'Permitir solo al usar la app'. Luego vuelve a TapSOS e inténtalo de nuevo. Si el GPS está apagado, actívalo desde el panel de ajustes rápidos de tu teléfono.",
    faq8q: "¿Cómo establezco el número de llamada de emergencia?",
    faq8a: "Ve a Ajustes › Número de Emergencia e introduce el número de tu país (ej. 112 en España/Europa, 911 en USA/México, 999 en UK, 000 en Australia). La app intenta detectarlo automáticamente, pero puedes cambiarlo manualmente.",
    faq9q: "¿Cómo añado el widget de TapSOS a mi pantalla de inicio?",
    faq9a: "En Android: mantén pulsada una zona vacía de tu pantalla de inicio › Widgets › TapSOS. Coloca el widget. Muestra los botones SOS, Llamada y WhatsApp directamente en tu escritorio. En iOS: requiere configuración adicional en Xcode (en desarrollo).",
    faq10q: "¿TapSOS es gratis? ¿Hay suscripciones?",
    faq10a: "TapSOS es completamente gratuito. Se financia con publicidad de banner discreta (Google AdMob). No hay suscripciones, compras integradas ni costes ocultos.",
  },

  /* ══════════════════════════════════════════════════════════
     FRANÇAIS
  ══════════════════════════════════════════════════════════ */
  fr: {
    footerPrivacy: "Politique de confidentialité", footerTerms: "Conditions générales",
    footerSupport: "Assistance et FAQ", footerRights: "© 2026 TapSOS. Tous droits réservés.",
    heroTitle: "Aide d'urgence en un clic",
    heroDesc: "TapSOS est l'application d'urgence la plus simple, conçue pour tous — en particulier les seniors. Déclenchez une sirène, appelez les secours et partagez votre position GPS via WhatsApp instantanément.",
    btnApple: "App Store", btnGoogle: "Google Play",
    feat1Title: "Alarme SOS instantanée", feat1Desc: "Un appui déclenche une puissante sirène à plein volume.",
    feat2Title: "Appel d'urgence", feat2Desc: "Appelle directement votre numéro d'urgence configuré.",
    feat3Title: "Localisation WhatsApp", feat3Desc: "Envoie vos coordonnées GPS en temps réel à jusqu'à 5 contacts.",
    feat4Title: "Secouer pour activer", feat4Desc: "Secouez le téléphone pour déclencher l'alarme sans les mains.",
    feat5Title: "Widget écran d'accueil", feat5Desc: "Placez les boutons SOS sur votre écran d'accueil.",
    feat6Title: "10 sons d'alarme", feat6Desc: "Choisissez parmi 10 sirènes différentes.",
    privTitle: "Politique de confidentialité", termsTitle: "Conditions générales",
    supportTitle: "Assistance et FAQ",
    supportDesc: "Besoin d'aide ? Trouvez vos réponses ci-dessous ou envoyez-nous un message.",
    supportBtn: "Envoyer un e-mail",
    faqTitle: "Foire aux questions",
    faq1q: "TapSOS a-t-il besoin d'une connexion Internet ?",
    faq1a: "Uniquement pour envoyer le message de localisation WhatsApp. La sirène, la vibration et l'appel d'urgence fonctionnent sans Internet.",
    faq2q: "Mes données personnelles sont-elles stockées sur un serveur ?",
    faq2a: "Non. TapSOS stocke tout localement sur votre appareil. Nous n'avons aucun serveur contenant vos données.",
    faq3q: "Comment configurer les contacts d'urgence WhatsApp ?",
    faq3a: "Allez dans Paramètres › Contact WhatsApp › Ajouter depuis les contacts. Important : le numéro doit inclure l'indicatif international (ex. +33 pour la France). Vous pouvez ajouter jusqu'à 5 contacts.",
    faq4q: "Le bouton WhatsApp ne fonctionne pas. Que faire ?",
    faq4a: "Vérifiez : 1) WhatsApp est installé. 2) Vous avez ajouté un contact dans Paramètres. 3) La localisation (GPS) est activée. 4) Le numéro de contact inclut l'indicatif (+33, +1, +44, etc.).",
    faq5q: "Comment changer le son de l'alarme ?",
    faq5a: "Allez dans Paramètres › Son de l'alarme. Appuyez sur ▶ pour écouter, puis sélectionnez et enregistrez.",
    faq6q: "Comment fonctionne 'Secouer pour activer' ?",
    faq6a: "Secouez rapidement votre téléphone 2 à 3 fois pour déclencher l'alarme. Activez/désactivez dans Paramètres.",
    faq7q: "L'app indique 'Autorisation de localisation refusée'. Comment corriger ?",
    faq7a: "Allez dans Paramètres du téléphone › Applications › TapSOS › Autorisations › Localisation › Autoriser. Activez aussi le GPS si nécessaire.",
    faq8q: "Comment définir le numéro d'appel d'urgence ?",
    faq8a: "Allez dans Paramètres › Numéro d'urgence (ex. 112 en Europe, 15 SAMU en France). L'app détecte votre pays automatiquement.",
    faq9q: "Comment ajouter le widget TapSOS à l'écran d'accueil ?",
    faq9a: "Sur Android : appui long sur l'écran d'accueil › Widgets › TapSOS. Sur iOS : fonctionnalité en cours de développement.",
    faq10q: "TapSOS est-il gratuit ? Y a-t-il des abonnements ?",
    faq10a: "TapSOS est entièrement gratuit, financé par des publicités banner discrètes. Aucun abonnement, aucun achat intégré.",
  },

  /* ══════════════════════════════════════════════════════════
     DEUTSCH
  ══════════════════════════════════════════════════════════ */
  de: {
    footerPrivacy: "Datenschutzrichtlinie", footerTerms: "AGB",
    footerSupport: "Support & FAQ", footerRights: "© 2026 TapSOS. Alle Rechte vorbehalten.",
    heroTitle: "Notfallhilfe, einen Tipp entfernt",
    heroDesc: "TapSOS ist die einfachste Notfall-App für jeden — besonders für Senioren. Sirene auslösen, Notfall anrufen und GPS-Standort sofort per WhatsApp teilen.",
    btnApple: "App Store", btnGoogle: "Google Play",
    feat1Title: "Sofort-SOS-Alarm", feat1Desc: "Ein Tipp löst eine leistungsstarke Sirene aus.",
    feat2Title: "Notruf", feat2Desc: "Ruft direkt Ihre konfigurierte Notrufnummer an.",
    feat3Title: "WhatsApp-Standort", feat3Desc: "Sendet GPS-Koordinaten an bis zu 5 Kontakte.",
    feat4Title: "Schütteln zum Aktivieren", feat4Desc: "Telefon schütteln, um den Alarm freihändig auszulösen.",
    feat5Title: "Home-Screen-Widget", feat5Desc: "SOS-Tasten direkt auf dem Startbildschirm.",
    feat6Title: "10 Alarmtöne", feat6Desc: "Wählen Sie aus 10 verschiedenen Sirenenklängen.",
    privTitle: "Datenschutzrichtlinie", termsTitle: "Allgemeine Geschäftsbedingungen",
    supportTitle: "Support & FAQ",
    supportDesc: "Brauchen Sie Hilfe? Antworten finden Sie unten oder schreiben Sie uns.",
    supportBtn: "E-Mail senden",
    faqTitle: "Häufig gestellte Fragen",
    faq1q: "Benötigt TapSOS eine Internetverbindung?",
    faq1a: "Nur für WhatsApp-Ortsnachrichten. Sirene, Vibration und Notruf funktionieren offline.",
    faq2q: "Werden meine Daten auf einem Server gespeichert?",
    faq2a: "Nein. Alles wird lokal auf Ihrem Gerät gespeichert. Keine Serverdaten.",
    faq3q: "Wie richte ich WhatsApp-Notfallkontakte ein?",
    faq3a: "Einstellungen › WhatsApp-Kontakt › Aus Kontakten hinzufügen. Nummer muss die Ländervorwahl enthalten (z.B. +49 für Deutschland). Bis zu 5 Kontakte möglich.",
    faq4q: "Die WhatsApp-Schaltfläche funktioniert nicht. Was tun?",
    faq4a: "Prüfen Sie: 1) WhatsApp ist installiert. 2) Kontakt in Einstellungen hinzugefügt. 3) GPS ist aktiviert. 4) Nummer enthält Ländervorwahl (+49, +1, +44 usw.).",
    faq5q: "Wie ändere ich den Alarmton?",
    faq5a: "Einstellungen › Alarmsirene. ▶ drücken zum Vorhören, dann auswählen und speichern.",
    faq6q: "Wie funktioniert 'Schütteln zum Aktivieren'?",
    faq6a: "Telefon 2-3 Mal schütteln, um Alarm auszulösen. In Einstellungen aktivierbar/deaktivierbar.",
    faq7q: "App zeigt 'Standortberechtigung verweigert'. Wie beheben?",
    faq7a: "Telefoneinstellungen › Apps › TapSOS › Berechtigungen › Standort › Erlauben. GPS ebenfalls aktivieren.",
    faq8q: "Wie stelle ich die Notrufnummer ein?",
    faq8a: "Einstellungen › Notrufnummer (z.B. 112 in Europa, 110 Polizei / 112 Feuerwehr). App erkennt Land automatisch.",
    faq9q: "Wie füge ich das TapSOS-Widget zum Startbildschirm hinzu?",
    faq9a: "Android: Langer Druck auf Startbildschirm › Widgets › TapSOS. iOS: In Entwicklung.",
    faq10q: "Ist TapSOS kostenlos?",
    faq10a: "Ja, vollständig kostenlos. Finanziert durch dezente Banner-Werbung. Keine Abonnements.",
  },

  /* ══════════════════════════════════════════════════════════
     ITALIANO
  ══════════════════════════════════════════════════════════ */
  it: {
    footerPrivacy: "Informativa sulla privacy", footerTerms: "Termini e condizioni",
    footerSupport: "Supporto e FAQ", footerRights: "© 2026 TapSOS. Tutti i diritti riservati.",
    heroTitle: "Aiuto di emergenza a un tocco",
    heroDesc: "TapSOS è l'app di emergenza più accessibile per tutti — soprattutto anziani. Attiva sirena, chiama soccorsi e condividi la posizione GPS via WhatsApp all'istante.",
    btnApple: "App Store", btnGoogle: "Google Play",
    feat1Title: "Allarme SOS immediato", feat1Desc: "Un tocco attiva una potente sirena a volume massimo.",
    feat2Title: "Chiamata di emergenza", feat2Desc: "Chiama direttamente il numero configurato.",
    feat3Title: "Posizione WhatsApp", feat3Desc: "Invia coordinate GPS in tempo reale a 5 contatti.",
    feat4Title: "Agita per attivare", feat4Desc: "Agita il telefono per attivare l'allarme senza mani.",
    feat5Title: "Widget schermata Home", feat5Desc: "Tasti SOS direttamente sulla schermata Home.",
    feat6Title: "10 suoni allarme", feat6Desc: "Scegli tra 10 sirene diverse.",
    privTitle: "Informativa sulla privacy", termsTitle: "Termini e condizioni",
    supportTitle: "Supporto e FAQ",
    supportDesc: "Hai bisogno di aiuto? Trova le risposte qui sotto o scrivici.",
    supportBtn: "Invia e-mail",
    faqTitle: "Domande frequenti",
    faq1q: "TapSOS ha bisogno di una connessione Internet?",
    faq1a: "Solo per inviare il messaggio di posizione WhatsApp. Sirena, vibrazione e chiamata funzionano offline.",
    faq2q: "I miei dati personali vengono salvati su un server?",
    faq2a: "No. TapSOS salva tutto localmente sul dispositivo. Nessun server contiene i tuoi dati.",
    faq3q: "Come configuro i contatti di emergenza WhatsApp?",
    faq3a: "Impostazioni › Contatto WhatsApp › Aggiungi dai contatti. Il numero deve includere il prefisso internazionale (es. +39 per Italia). Fino a 5 contatti.",
    faq4q: "Il pulsante WhatsApp non funziona. Cosa faccio?",
    faq4a: "Verifica: 1) WhatsApp installato. 2) Contatto aggiunto. 3) GPS attivo. 4) Numero con prefisso (+39, +1, +44, ecc.).",
    faq5q: "Come cambio il suono dell'allarme?",
    faq5a: "Impostazioni › Sirena di allarme. Premi ▶ per ascoltare, seleziona e salva.",
    faq6q: "Come funziona 'Agita per attivare'?",
    faq6a: "Agita il telefono 2-3 volte rapidamente per attivare l'allarme. Attivabile/disattivabile in Impostazioni.",
    faq7q: "L'app dice 'Autorizzazione posizione negata'. Come risolvere?",
    faq7a: "Impostazioni telefono › App › TapSOS › Autorizzazioni › Posizione › Consenti. Attiva anche il GPS.",
    faq8q: "Come imposto il numero di emergenza?",
    faq8a: "Impostazioni › Numero di emergenza (es. 112 in Europa, 118 ambulanza Italia). L'app rileva il paese automaticamente.",
    faq9q: "Come aggiungo il widget TapSOS alla schermata Home?",
    faq9a: "Android: tieni premuta la schermata Home › Widget › TapSOS. iOS: funzione in sviluppo.",
    faq10q: "TapSOS è gratuito?",
    faq10a: "Sì, completamente gratuito. Finanziato da pubblicità banner discreta. Nessun abbonamento.",
  },

  /* ══════════════════════════════════════════════════════════
     PORTUGUÊS
  ══════════════════════════════════════════════════════════ */
  pt: {
    footerPrivacy: "Política de Privacidade", footerTerms: "Termos e Condições",
    footerSupport: "Suporte e FAQ", footerRights: "© 2026 TapSOS. Todos os direitos reservados.",
    heroTitle: "Ajuda de Emergência a um Toque",
    heroDesc: "TapSOS é o app de emergência mais acessível para todos — especialmente idosos. Ative sirene, ligue para emergências e compartilhe sua localização GPS via WhatsApp instantaneamente.",
    btnApple: "App Store", btnGoogle: "Google Play",
    feat1Title: "Alarme SOS imediato", feat1Desc: "Um toque ativa uma poderosa sirene em volume máximo.",
    feat2Title: "Chamada de emergência", feat2Desc: "Liga diretamente para o número configurado.",
    feat3Title: "Localização WhatsApp", feat3Desc: "Envia coordenadas GPS em tempo real para 5 contatos.",
    feat4Title: "Agitar para ativar", feat4Desc: "Agite o telefone para ativar o alarme sem as mãos.",
    feat5Title: "Widget tela inicial", feat5Desc: "Botões SOS diretamente na tela inicial.",
    feat6Title: "10 sons de alarme", feat6Desc: "Escolha entre 10 sirenes diferentes.",
    privTitle: "Política de Privacidade", termsTitle: "Termos e Condições",
    supportTitle: "Suporte e FAQ",
    supportDesc: "Precisa de ajuda? Encontre respostas abaixo ou envie uma mensagem.",
    supportBtn: "Enviar E-mail",
    faqTitle: "Perguntas Frequentes",
    faq1q: "O TapSOS precisa de conexão com a internet?",
    faq1a: "Somente para enviar a mensagem de localização do WhatsApp. A sirene, vibração e ligação funcionam offline.",
    faq2q: "Meus dados pessoais são armazenados em servidor?",
    faq2a: "Não. O TapSOS armazena tudo localmente no dispositivo. Nenhum servidor contém seus dados.",
    faq3q: "Como configuro os contatos de emergência do WhatsApp?",
    faq3a: "Configurações › Contato WhatsApp › Adicionar dos contatos. O número deve incluir o código do país (ex. +55 para Brasil). Até 5 contatos.",
    faq4q: "O botão WhatsApp não funciona. O que fazer?",
    faq4a: "Verifique: 1) WhatsApp instalado. 2) Contato adicionado. 3) GPS ativo. 4) Número com código (+55, +351, +1, etc.).",
    faq5q: "Como mudo o som do alarme?",
    faq5a: "Configurações › Som de alarme. Pressione ▶ para ouvir, selecione e salve.",
    faq6q: "Como funciona 'Agitar para ativar'?",
    faq6a: "Agite o telefone 2-3 vezes rapidamente para ativar o alarme. Ative/desative em Configurações.",
    faq7q: "O app diz 'Permissão de localização negada'. Como resolver?",
    faq7a: "Configurações do telefone › Aplicativos › TapSOS › Permissões › Localização › Permitir. Ative também o GPS.",
    faq8q: "Como defino o número de emergência?",
    faq8a: "Configurações › Número de Emergência (ex. 192 SAMU, 193 bombeiros, 190 polícia no Brasil). O app detecta o país automaticamente.",
    faq9q: "Como adiciono o widget TapSOS à tela inicial?",
    faq9a: "Android: pressione e segure a tela inicial › Widgets › TapSOS. iOS: funcionalidade em desenvolvimento.",
    faq10q: "O TapSOS é gratuito?",
    faq10a: "Sim, totalmente gratuito. Financiado por publicidade banner discreta. Sem assinaturas.",
  },

  /* ══════════════════════════════════════════════════════════
     РУССКИЙ
  ══════════════════════════════════════════════════════════ */
  ru: {
    footerPrivacy: "Конфиденциальность", footerTerms: "Условия использования",
    footerSupport: "Поддержка и FAQ", footerRights: "© 2026 TapSOS. Все права защищены.",
    heroTitle: "Экстренная помощь в один клик",
    heroDesc: "TapSOS — самое простое приложение для экстренных ситуаций для всех, особенно пожилых. Сирена, звонок в скорую и отправка GPS-координат в WhatsApp мгновенно.",
    btnApple: "App Store", btnGoogle: "Google Play",
    feat1Title: "Мгновенная SOS-тревога", feat1Desc: "Одно нажатие — мощная сирена на полную громкость.",
    feat2Title: "Экстренный звонок", feat2Desc: "Прямой звонок на настроенный номер экстренной службы.",
    feat3Title: "Геолокация в WhatsApp", feat3Desc: "Отправка GPS-координат до 5 контактам.",
    feat4Title: "Встряхните для активации", feat4Desc: "Встряхните телефон для запуска сирены.",
    feat5Title: "Виджет рабочего стола", feat5Desc: "Кнопки SOS прямо на рабочем столе.",
    feat6Title: "10 звуков тревоги", feat6Desc: "Выберите из 10 различных сирен.",
    privTitle: "Политика конфиденциальности", termsTitle: "Условия использования",
    supportTitle: "Поддержка и FAQ",
    supportDesc: "Нужна помощь? Найдите ответы ниже или напишите нам.",
    supportBtn: "Отправить E-mail",
    faqTitle: "Часто задаваемые вопросы",
    faq1q: "Нужен ли TapSOS интернет?",
    faq1a: "Только для отправки геолокации в WhatsApp. Сирена, вибрация и звонок работают без интернета.",
    faq2q: "Хранятся ли мои данные на сервере?",
    faq2a: "Нет. Всё хранится локально на вашем устройстве. У нас нет серверов с вашими данными.",
    faq3q: "Как настроить контакты WhatsApp для экстренных случаев?",
    faq3a: "Настройки › Контакт WhatsApp › Добавить из контактов. Номер должен содержать код страны (напр. +7 для России). До 5 контактов.",
    faq4q: "Кнопка WhatsApp не работает. Что делать?",
    faq4a: "Проверьте: 1) WhatsApp установлен. 2) Добавлен контакт. 3) GPS включён. 4) Номер содержит код страны (+7, +1, +44 и т.д.).",
    faq5q: "Как изменить звук тревоги?",
    faq5a: "Настройки › Сирена тревоги. Нажмите ▶ для прослушивания, выберите и сохраните.",
    faq6q: "Как работает 'Встряхнуть для активации'?",
    faq6a: "Встряхните телефон 2-3 раза, чтобы включить тревогу. Включается/отключается в Настройках.",
    faq7q: "Приложение показывает 'Доступ к геолокации запрещён'. Как исправить?",
    faq7a: "Настройки телефона › Приложения › TapSOS › Разрешения › Местоположение › Разрешить. Включите GPS.",
    faq8q: "Как установить номер экстренной службы?",
    faq8a: "Настройки › Экстренный номер (напр. 112 в России и Европе). Приложение определяет страну автоматически.",
    faq9q: "Как добавить виджет TapSOS на рабочий стол?",
    faq9a: "Android: нажмите и удерживайте экран › Виджеты › TapSOS. iOS: в разработке.",
    faq10q: "TapSOS бесплатный?",
    faq10a: "Да, полностью бесплатный. Поддерживается ненавязчивой баннерной рекламой. Без подписок.",
  },

  /* ══════════════════════════════════════════════════════════
     中文
  ══════════════════════════════════════════════════════════ */
  zh: {
    footerPrivacy: "隐私政策", footerTerms: "条款和条件",
    footerSupport: "支持与常见问题", footerRights: "© 2026 TapSOS. 保留所有权利。",
    heroTitle: "紧急援助，一触即发",
    heroDesc: "TapSOS 是最简单的紧急应用，专为所有人设计——尤其是老年人。立即触发警报、拨打急救电话并通过 WhatsApp 发送 GPS 位置。",
    btnApple: "App Store", btnGoogle: "Google Play",
    feat1Title: "即时SOS警报", feat1Desc: "一键触发全音量强力警报。",
    feat2Title: "紧急呼叫", feat2Desc: "直接拨打预设的急救号码。",
    feat3Title: "WhatsApp位置", feat3Desc: "实时向5位联系人发送GPS坐标。",
    feat4Title: "摇动激活", feat4Desc: "摇动手机即可免手动触发警报。",
    feat5Title: "主屏幕小部件", feat5Desc: "直接在主屏幕上放置SOS按钮。",
    feat6Title: "10种警报声", feat6Desc: "从10种不同的警报声中选择。",
    privTitle: "隐私政策", termsTitle: "条款和条件",
    supportTitle: "支持与常见问题",
    supportDesc: "需要帮助？在下方查找答案或给我们发送消息。",
    supportBtn: "发送电子邮件",
    faqTitle: "常见问题",
    faq1q: "TapSOS需要互联网连接吗？",
    faq1a: "仅发送WhatsApp位置消息时需要。SOS警报、振动和紧急通话可完全离线使用。",
    faq2q: "我的个人数据会存储在服务器上吗？",
    faq2a: "不会。TapSOS将所有内容本地存储在您的设备上。我们没有存储您数据的服务器。",
    faq3q: "如何设置WhatsApp紧急联系人？",
    faq3a: "设置 › WhatsApp联系人 › 从通讯录添加。号码必须包含国家代码（例如中国+86）。最多5个联系人。",
    faq4q: "WhatsApp按钮不起作用怎么办？",
    faq4a: "检查：1) 已安装WhatsApp。2) 已在设置中添加联系人。3) GPS已启用。4) 号码包含国家代码（+86、+1、+44等）。",
    faq5q: "如何更改警报声音？",
    faq5a: "设置 › 警报声。按▶预览，选择后保存。",
    faq6q: "'摇动激活'如何工作？",
    faq6a: "快速摇动手机2-3次即可触发警报。可在设置中启用/禁用。",
    faq7q: "应用显示'位置权限被拒绝'怎么解决？",
    faq7a: "手机设置 › 应用 › TapSOS › 权限 › 位置 › 允许。同时开启GPS。",
    faq8q: "如何设置急救电话号码？",
    faq8a: "设置 › 紧急号码（如中国120急救）。应用会自动检测您的国家。",
    faq9q: "如何将TapSOS小部件添加到主屏幕？",
    faq9a: "Android：长按主屏幕 › 小部件 › TapSOS。iOS：功能开发中。",
    faq10q: "TapSOS免费吗？",
    faq10a: "是的，完全免费。通过低调的横幅广告支持运营，没有订阅或内购。",
  },

  /* ══════════════════════════════════════════════════════════
     日本語
  ══════════════════════════════════════════════════════════ */
  ja: {
    footerPrivacy: "プライバシーポリシー", footerTerms: "利用規約",
    footerSupport: "サポート・よくある質問", footerRights: "© 2026 TapSOS. All rights reserved.",
    heroTitle: "ワンタップで緊急ヘルプ",
    heroDesc: "TapSOSはすべての方—特に高齢者向けの最もシンプルな緊急アプリ。サイレンを鳴らし、救急に電話し、WhatsAppでGPS位置を即座に送信。",
    btnApple: "App Store", btnGoogle: "Google Play",
    feat1Title: "即時SOSアラーム", feat1Desc: "1タップで全音量の強力なサイレン。",
    feat2Title: "緊急通報", feat2Desc: "設定した緊急番号に直接電話。",
    feat3Title: "WhatsApp位置情報", feat3Desc: "リアルタイムGPS座標を最大5人に送信。",
    feat4Title: "振って起動", feat4Desc: "スマホを振ってハンズフリーでアラーム起動。",
    feat5Title: "ホーム画面ウィジェット", feat5Desc: "ホーム画面に直接SOSボタンを配置。",
    feat6Title: "10種のアラーム音", feat6Desc: "10種類のサイレン音から選択。",
    privTitle: "プライバシーポリシー", termsTitle: "利用規約",
    supportTitle: "サポート・よくある質問",
    supportDesc: "お困りですか？以下で回答を探すか、メッセージをお送りください。",
    supportBtn: "メールを送信",
    faqTitle: "よくある質問",
    faq1q: "TapSOSにはインターネット接続が必要ですか？",
    faq1a: "WhatsApp位置情報送信のみ必要です。SOSサイレン、振動、緊急通話はオフラインで動作します。",
    faq2q: "個人データはサーバーに保存されますか？",
    faq2a: "いいえ。TapSOSはすべてを端末にローカル保存します。サーバーにデータはありません。",
    faq3q: "WhatsApp緊急連絡先の設定方法は？",
    faq3a: "設定 › WhatsAppの連絡先 › 連絡先から追加。番号には国番号が必要です（日本: +81）。最大5件。",
    faq4q: "WhatsAppボタンが機能しません。どうすれば？",
    faq4a: "確認事項: 1) WhatsAppがインストールされている 2) 設定で連絡先を追加済み 3) GPSが有効 4) 番号に国番号を含む（+81、+1など）。",
    faq5q: "アラーム音の変更方法は？",
    faq5a: "設定 › 警報サイレン。▶で試聴し、選択して保存。",
    faq6q: "「振って起動」の使い方は？",
    faq6a: "スマホを素早く2〜3回振るとアラームが起動します。設定でオン/オフ可能。",
    faq7q: "「位置情報の許可が拒否」と表示されます。解決方法は？",
    faq7a: "設定 › アプリ › TapSOS › 権限 › 位置情報 › 許可する。GPSもオンにしてください。",
    faq8q: "緊急電話番号の設定方法は？",
    faq8a: "設定 › 緊急番号（日本: 119 救急/消防、110 警察）。アプリが国を自動検出します。",
    faq9q: "ウィジェットをホーム画面に追加する方法は？",
    faq9a: "Android: ホーム画面を長押し › ウィジェット › TapSOS。iOS: 開発中。",
    faq10q: "TapSOSは無料ですか？",
    faq10a: "はい、完全無料です。控えめなバナー広告で運営。サブスクリプションなし。",
  },

  /* ══════════════════════════════════════════════════════════
     العربية
  ══════════════════════════════════════════════════════════ */
  ar: {
    footerPrivacy: "سياسة الخصوصية", footerTerms: "الشروط والأحكام",
    footerSupport: "الدعم والأسئلة الشائعة", footerRights: "© 2026 TapSOS. جميع الحقوق محفوظة.",
    heroTitle: "مساعدة الطوارئ بلمسة واحدة",
    heroDesc: "TapSOS هو أسهل تطبيق للطوارئ للجميع — وخاصة كبار السن. أطلق صفارة إنذار، اتصل بالطوارئ، وأرسل موقعك عبر WhatsApp فوراً.",
    btnApple: "App Store", btnGoogle: "Google Play",
    feat1Title: "إنذار SOS فوري", feat1Desc: "لمسة واحدة تطلق صفارة قوية بأعلى مستوى صوت.",
    feat2Title: "مكالمة طوارئ", feat2Desc: "يتصل مباشرة برقم الطوارئ المحدد.",
    feat3Title: "الموقع عبر WhatsApp", feat3Desc: "يرسل إحداثيات GPS الفورية لـ 5 جهات اتصال.",
    feat4Title: "هز للتفعيل", feat4Desc: "هز الهاتف لتفعيل الإنذار دون استخدام اليدين.",
    feat5Title: "أداة الشاشة الرئيسية", feat5Desc: "أزرار SOS مباشرة على شاشتك الرئيسية.",
    feat6Title: "10 أصوات إنذار", feat6Desc: "اختر من بين 10 أصوات صفارات مختلفة.",
    privTitle: "سياسة الخصوصية", termsTitle: "الشروط والأحكام",
    supportTitle: "الدعم والأسئلة الشائعة",
    supportDesc: "هل تحتاج مساعدة؟ ابحث عن إجابات أدناه أو أرسل لنا رسالة.",
    supportBtn: "إرسال بريد إلكتروني",
    faqTitle: "الأسئلة الشائعة",
    faq1q: "هل يحتاج TapSOS إلى اتصال بالإنترنت؟",
    faq1a: "فقط لإرسال رسالة الموقع عبر WhatsApp. تعمل صفارة الإنذار والاهتزاز والمكالمة الهاتفية بالكامل دون إنترنت.",
    faq2q: "هل يتم تخزين بياناتي الشخصية على خادم؟",
    faq2a: "لا. يخزّن TapSOS كل شيء محلياً على جهازك. ليس لدينا خوادم تحتوي على بياناتك.",
    faq3q: "كيف أضيف جهات اتصال الطوارئ على WhatsApp؟",
    faq3a: "الإعدادات › جهة اتصال WhatsApp › إضافة من جهات الاتصال. يجب أن يتضمن الرقم رمز البلد الدولي (مثال +966 للسعودية، +20 لمصر). يمكن إضافة 5 جهات اتصال.",
    faq4q: "زر WhatsApp لا يعمل. ماذا أفعل؟",
    faq4a: "تحقق من: 1) تثبيت WhatsApp. 2) إضافة جهة اتصال في الإعدادات. 3) تفعيل GPS. 4) الرقم يحتوي على رمز البلد (+966، +1، +44، إلخ).",
    faq5q: "كيف أغير صوت الإنذار؟",
    faq5a: "الإعدادات › صفارة الإنذار. اضغط ▶ للاستماع، اختر وحفظ.",
    faq6q: "كيف تعمل ميزة 'هز للتفعيل'؟",
    faq6a: "هز الهاتف بسرعة 2-3 مرات لتشغيل الإنذار. يمكن تفعيلها/إيقافها من الإعدادات.",
    faq7q: "التطبيق يظهر 'تم رفض إذن الموقع'. كيف أحل المشكلة؟",
    faq7a: "إعدادات الهاتف › التطبيقات › TapSOS › الأذونات › الموقع › السماح. فعّل GPS أيضاً.",
    faq8q: "كيف أضبط رقم الطوارئ؟",
    faq8a: "الإعدادات › رقم الطوارئ (مثال: 911 السعودية، 123 الإمارات، 123 مصر). يكتشف التطبيق بلدك تلقائياً.",
    faq9q: "كيف أضيف أداة TapSOS إلى شاشتي الرئيسية؟",
    faq9a: "Android: اضغط مطولاً على الشاشة الرئيسية › الأدوات › TapSOS. iOS: الميزة قيد التطوير.",
    faq10q: "هل TapSOS مجاني؟",
    faq10a: "نعم، مجاني تماماً. يتم دعمه بإعلانات بانر غير مزعجة. لا اشتراكات ولا مشتريات.",
  },
};

/* ══════════════════════════════════════════════════════════
   ENGINE
══════════════════════════════════════════════════════════ */
document.addEventListener('DOMContentLoaded', () => {
  const langSelector = document.getElementById('lang-selector');
  const userLang = (navigator.language || navigator.userLanguage || 'en').split('-')[0];
  let currentLang = translations[userLang] ? userLang : 'en';

  if (langSelector) {
    langSelector.value = currentLang;
    langSelector.addEventListener('change', e => setLanguage(e.target.value));
  }
  setLanguage(currentLang);
});

function setLanguage(lang) {
  const t = translations[lang] || translations['en'];

  // Simple text nodes
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) el.textContent = t[key];
  });

  // HTML nodes (for rich content like <a> tags inside)
  document.querySelectorAll('[data-i18n-html]').forEach(el => {
    const key = el.getAttribute('data-i18n-html');
    if (t[key] !== undefined) el.innerHTML = t[key];
  });

  // RTL for Arabic
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  document.body.style.fontFamily = lang === 'ar'
    ? "'Cairo', sans-serif"
    : "'Inter', -apple-system, sans-serif";
}
